# .zshrc - Custom config for zsh, with Yazt settings
# --------------------------------------------------
# See the Yazt wiki for more info.

## Installation place of Yazt.
yazt="$HOME/.yazt"

## Your Yazt theme. If not picked, the default (default.yzt) will be picked.
yazttheme="default"

## Turns on Yazp, the plugin backend for Yazt.
## WARN: No plugins are installed by default.
yazpon=false

 ## Yazp plugins. Put it in this format:
 ## yazpplugins=(
 ## plugin 
 ## otherplugin
 ## )
 yazpplugins=(
 git
 brew
 )

# Initializes Yazt.
source "$yazt/yazt.sh"
